### ISSUE TITLE
Problem with get_proteomes.py

### ISSUE THREAD

**Issue by fmalmeida** [dani2s/ShadowCaster#1]
Hello,

I am currently trying to use ShadowCaster with my newly assembled _Klebsiella pneumoniae_ genome. However, when trying to download the NCBI proteomes with `get_proteomes.py` I get an error.

Command:
`python get_proteomes.py -n Klebsiella_pneumoniae -sp 25 -db`

Error:
```bash
esearch installed!

Downloading taxdump.tar.gz from NCBI FTP site (via HTTP)...
Done. Parsing...
Loading node names...
2127236 names loaded.
210066 synonyms loaded.
Loading nodes...
2127236 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /home/falmeida/.etetoolkit/taxa.sqlite ...
 2127000 generating entries... 
Uploading to /home/falmeida/.etetoolkit/taxa.sqlite

Inserting synonyms:      210000 
Inserting taxid merges:  50000 
Inserting taxids:       2125000 
get_proteomes.py:82: FutureWarning: read_table is deprecated, use read_csv instead.
  df1 = pd.read_table(url, sep='\t', header=None)
Traceback (most recent call last):
  File "get_proteomes.py", line 213, in <module>
    main(args)
  File "get_proteomes.py", line 177, in main
    idsFinal = get_ids(mainDict[i][1], args.sp_name, mainDict[i][0], idsFinal)
  File "get_proteomes.py", line 83, in get_ids
    df1.columns = ['name', 'url']
  File "/home/falmeida/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 5080, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/falmeida/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 638, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/falmeida/.local/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 155, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
```

I wonder what could it be.

All dependencies seem to have been properly installed since installation had no errors.

Thanks in advance.

**Comment by dani2s** [comment]
Hello,
 
Thanks for trying to use ShadowCaster. I tried the command line that you provided and didn't have this issue. If all dependencies were correctly installed, I could suggest some problems trying to connect with the NCBI FTP site. Sometimes this can be a temporary problem; please wait and try to run the script again in an hour or two. 
I am closing this issue. If it is still a problem, please feel free to re-open it.
