### ISSUE TITLE
There is a problem when I used ShadowCaster   RuntimeError: maximum recursion

### ISSUE THREAD

**Issue by hdxieruize** [dani2s/ShadowCaster#2]
Dear all:
I encounter a problem when I used ShadowCaster to find HGT, but I don't know how to address it.
The errors as below:
Traceback (most recent call last):
  File "/home/xieruize/Python2/bin/shadowcaster", line 4, in <module>
    __import__('pkg_resources').run_script('ShadowCaster==0.9.2', 'shadowcaster')
  File "/home/xieruize/Python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  ......
  File "/home/xieruize/Python2/lib/python2.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 364, in __new__
    if isinstance(toklist, cls):
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by dani2s** [comment]
Hello,
Sorry to hear that you had an issue with ShadowCaster. Do you have the same problem when you run the command:
`shadowcaster --help`

If that is the case, what is your system version? And what is the installed version of the python package called setuptools? You can find this by running:
`pip show setuptools`
